/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.PraktikumPBOL.GUIPerpustakaan;

import javax.swing.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * @author Markus
 */
public class LayerKoleksi extends javax.swing.JDialog {

    /**
     * Creates new form LayerKoleksi
     */
    public LayerKoleksi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        addOnProgram();
    }

    //program tambahan yagn dipanggil dikonstrukstor saat program dijalankan
    private void addOnProgram() {
        statusPinjamButtonGroup.setSelected(falsebutton.getModel(), false); //mengatur nilai tombol kedua ke false
        secondUniversalLabel.setVisible(false); //saat program dijalankan label tidak terlihat
        secondUniversalTextInput.setVisible(false); //saat program dijalankan input text tidak terlihat
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusPinjamButtonGroup = new javax.swing.ButtonGroup();
        titlelabel = new javax.swing.JLabel();
        idKoleksiLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        judulLabel = new javax.swing.JLabel();
        judulTextField = new javax.swing.JTextField();
        penerbitTextField = new javax.swing.JTextField();
        penerbitLabel = new javax.swing.JLabel();
        namaLabel2 = new javax.swing.JLabel();
        tipeComboBox = new javax.swing.JComboBox<>();
        firstUniversalTextInput = new javax.swing.JTextField();
        firstUniversalLabel = new javax.swing.JLabel();
        kembaliButton = new javax.swing.JButton();
        tipeLabel = new javax.swing.JLabel();
        ulangiButton = new javax.swing.JButton();
        simpanButton = new javax.swing.JButton();
        trueButton = new javax.swing.JRadioButton();
        falsebutton = new javax.swing.JRadioButton();
        secondUniversalTextInput = new javax.swing.JTextField();
        secondUniversalLabel = new javax.swing.JLabel();
        isbnTextInput = new javax.swing.JTextField();
        isbnLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titlelabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        titlelabel.setText("KOLEKSI");
        titlelabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        idKoleksiLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        idKoleksiLabel.setText("ID Koleksi");

        idTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });

        judulLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        judulLabel.setText("Judul");

        judulTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judulTextFieldActionPerformed(evt);
            }
        });

        penerbitTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penerbitTextFieldActionPerformed(evt);
            }
        });

        penerbitLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        penerbitLabel.setText("Penerbit");

        namaLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        namaLabel2.setText("Status Pinjam");

        tipeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Disk", "Majalah", "Buku"}));
        tipeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipeComboBoxActionPerformed(evt);
            }
        });

        firstUniversalTextInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstUniversalTextInputActionPerformed(evt);
            }
        });

        firstUniversalLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        firstUniversalLabel.setText("Format");

        kembaliButton.setText("Kembali");
        kembaliButton.setBorder(null);
        kembaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliButtonActionPerformed(evt);
            }
        });

        tipeLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tipeLabel.setText("Tipe");

        ulangiButton.setText("Ulangi");
        ulangiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulangiButtonActionPerformed(evt);
            }
        });

        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        statusPinjamButtonGroup.add(trueButton);
        trueButton.setText("Boleh");
        trueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trueButtonActionPerformed(evt);
            }
        });

        statusPinjamButtonGroup.add(falsebutton);
        falsebutton.setText("Tidak");
        falsebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                falsebuttonActionPerformed(evt);
            }
        });

        secondUniversalTextInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondUniversalTextInputActionPerformed(evt);
            }
        });

        secondUniversalLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        secondUniversalLabel.setText("Volume");

        isbnTextInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnTextInputActionPerformed(evt);
            }
        });

        isbnLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        isbnLabel.setText("ISBN");

        exitButton.setText("X");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ulangiButton)
                                .addGap(18, 18, 18)
                                .addComponent(simpanButton)
                                .addGap(35, 35, 35))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(namaLabel2)
                                                        .addComponent(tipeLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(trueButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(falsebutton))
                                                        .addComponent(tipeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(judulLabel)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(judulTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(idKoleksiLabel)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(penerbitLabel)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(penerbitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(secondUniversalLabel)
                                                .addGap(18, 18, 18)
                                                .addComponent(secondUniversalTextInput, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(isbnLabel)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(isbnTextInput, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(firstUniversalLabel)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(firstUniversalTextInput, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(27, 27, 27))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(kembaliButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                                .addComponent(titlelabel)
                                .addGap(209, 209, 209)
                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(titlelabel))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(kembaliButton))))
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(idKoleksiLabel)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(isbnLabel)
                                                        .addComponent(isbnTextInput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(judulLabel)
                                                        .addComponent(judulTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(penerbitLabel)
                                                        .addComponent(penerbitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(firstUniversalLabel)
                                                        .addComponent(firstUniversalTextInput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(12, 12, 12)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(secondUniversalLabel)
                                                        .addComponent(secondUniversalTextInput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(namaLabel2)
                                        .addComponent(trueButton)
                                        .addComponent(falsebutton))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tipeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tipeLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ulangiButton)
                                        .addComponent(simpanButton))
                                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {
        dispose(); //Menghapus Dialog
    }


    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void judulTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void penerbitTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void firstUniversalTextInputActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void kembaliButtonActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false); //saat tombol ditekan, tampilan kelas ini tidak terlihat
    }

    //menjalankan program saat tombol ulangi ditekan
    private void ulangiButtonActionPerformed(java.awt.event.ActionEvent evt) {

        //mengembalikan karakter yang ada di input text ke kosong
        idTextField.setText("");
        judulTextField.setText("");
        penerbitTextField.setText("");
        firstUniversalTextInput.setText("");
        secondUniversalTextInput.setText("");
        isbnTextInput.setText("");

        //menghapus pilihan pada Button Group
        statusPinjamButtonGroup.clearSelection();
    }

    //menjalankan program saat tombol simpan di tekan
    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // nilai harus true semua agar JOptanePane ditampilkan
        boolean validate = isIdKoleksiStartWithLetter() && isUniversalInputInteger() && isInputFormatCorrect();
        String showAddonMessage = ""; //membuat variable baru dengan tipe String

        if (tipeComboBox.getSelectedIndex() == 0) { //jika item yang dipilih berindex 0
            showAddonMessage = ("\nFormat: " + firstUniversalTextInput.getText().substring(0,1).toUpperCase()+
                    firstUniversalTextInput.getText().substring(1).toLowerCase()+
                    "\nISBN: " + isbnTextInput.getText()); //String concat dan diassign ke variable yang dibuat di atas
        } else if (tipeComboBox.getSelectedIndex() == 1) { //jika item yang dipilih berindex 1
            showAddonMessage = ("\nSeri: " + firstUniversalTextInput.getText() +
                    "\nVolume: " + secondUniversalTextInput.getText() +
                    "\nISBN: " + isbnTextInput.getText()); //String concat dan diassign ke variable yang dibuat di atas
        } else if (tipeComboBox.getSelectedIndex() == 2) { //jika item yang dipilih berindex 2
            showAddonMessage = ("\nHalaman: " + firstUniversalTextInput.getText() +
                    "\nISBN: " + isbnTextInput.getText()); //String concat dan diassign ke varibale yang dibuat di atas
        }

        //jika true, menampilkan JOptanePane
        if (validate) {
            JOptionPane.showMessageDialog(this,
                    "ID: " + idTextField.getText().toUpperCase() +
                            "\nJudul: " + judulTextField.getText() +
                            "\nPenerbit: " + penerbitTextField.getText() +
                            "\nStatus Pinjam: " + statusPinjamButtonGroup.isSelected(trueButton.getModel()) +
                            "\nTipe: " + tipeComboBox.getModel().getSelectedItem() +
                            showAddonMessage); //menampilkan pesan dialog dengan JOptanePane, berisi String,
            // nilai diambil dari inputText dan juga variable showAddonDialog
        }
    }

    private void trueButtonActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void falsebuttonActionPerformed(java.awt.event.ActionEvent evt) {
    }

    //menjalankan program saat item di combobox dipilih, diambil nilai indexnya
    private void tipeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        if (tipeComboBox.getSelectedIndex() == 0) { //jika item yang dipilih berindex 0
            secondUniversalTextInput.setVisible(false); //membuat Input Text tidak terlihat
            secondUniversalLabel.setVisible(false); //membuat label tidak terlihat
            isbnLabel.setText("ISBN"); //mengganti text label
            firstUniversalLabel.setText("Format"); //mengganti text label
        } else if (tipeComboBox.getSelectedIndex() == 1) { //jika item yang dipiih berindex 1
            secondUniversalTextInput.setVisible(true); //membuat Input Text terlihat
            secondUniversalLabel.setVisible(true); //membuat label terlihat
            isbnLabel.setText("ISSN"); //mengganti text label
            firstUniversalLabel.setText("Seri"); //mengganti text label
            secondUniversalLabel.setText("Volume"); //mengganti text label
        } else if (tipeComboBox.getSelectedIndex() == 2) { //jika item yang dipilih berindex 2
            secondUniversalTextInput.setVisible(false); //membuat input text tidak terlihat
            secondUniversalLabel.setVisible(false); //membuat label tidak terlihat
            isbnLabel.setText("ISBN"); //mengganti text label
            firstUniversalLabel.setText("Halaman"); //mengganti text label
        }
    }

    private void secondUniversalTextInputActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void isbnTextInputActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private boolean isIdKoleksiStartWithLetter() {
        String[] tipePeminjam = {"^D", "^M", "^B"};
        String[] catchMessage = {"Disk", "Majalah", "Buku"};
        int choosenDropdown = tipeComboBox.getSelectedIndex();
        String showMessage = catchMessage[choosenDropdown];

        //membuat pattern regex, dimasukkan lewat parameter
        //Patterm.CASE_INSENSITIVE, agar nilai yang akan dibandingkan tidak peduli KAPITAL
        Pattern pattern = Pattern.compile(tipePeminjam[choosenDropdown], Pattern.CASE_INSENSITIVE);

        //mencari kesamaan pattern dengan nilai paramter
        Matcher matcher = pattern.matcher(idTextField.getText());

        try { //ekspresi try
            if (matcher.find()) {                       //jika matcher menemukan kesamaan
                return true;
            } else {                                    //jika selain benar
                throw new Exception();                  //melempar Exception baru
            }
        } catch (Exception e) {                         //menangkap Exception
            JOptionPane.showMessageDialog(this,     //menampilkan pesan dalam bentuk JOPtanePane
                    "ID " + showMessage + " dimulai dengan " +
                            showMessage.charAt(0));
        }
        return false;   //Return false, berarti nilai true tidak tercapai
    }

    private boolean isUniversalInputInteger() {

        //membuat pattern regex, dimasukkan lewat parameter
        Pattern pattern = Pattern.compile("\\d");

        //mencari kesamaan pattern dengan nilai paramter
        Matcher matcher1 = pattern.matcher(firstUniversalTextInput.getText());

        //mencari kesamaan pattern dengan nilai paramter
        Matcher matcher2 = pattern.matcher(secondUniversalTextInput.getText());

        switch (tipeComboBox.getSelectedIndex()) { //menjalankan jika menemukan nilai yang sesuai
            case 1:                                //nilai pertama
                try {                              //ekspresi try
                    if (matcher1.find() && matcher2.find()) {       //jika keuda matcher menemukan kesamaan
                        return true;
                    } else {                                        //pilihan selain benar
                        throw new Exception();                      //melempar Exception baru
                    }
                } catch (Exception e) {                             //menangkap Exception
                    JOptionPane.showMessageDialog(this,     //menampilkan pesan dalam bentuk JOPtanePane
                            firstUniversalLabel.getText() +
                                    " atau " + secondUniversalLabel.getText() +
                                    " Hanya Berisi Angka");
                }
                break;                                              //menghentikan switch case
            case 2:                             //nilai kedua
                try {                           //ekspresi try
                    if (matcher1.find()) {                          //jika matcher 1 menemukan kesamaan
                        return true;
                    } else {                                        //pilihan selain benar
                        throw new Exception();                      //melempar Exception baru
                    }
                } catch (Exception e) {                             //menangkap Exception
                    JOptionPane.showMessageDialog(this,     //menampilkan pesan dalam bentuk JOPtanePane
                            firstUniversalLabel.getText() +
                                    " Hanya Berisi Angka");
                }
                break;                                              //menghentikan switch case
            default:                            //nilai default, dijalankan jika kedua nilai tidak jalan
                return true;
        }
        return false;  //Return false, berarti nilai true tidak tercapai
    }

    private boolean isInputFormatCorrect() {
        String[] format = {"Audio", "Video", "Document"};

        //membuat pattern regex, dimasukkan lewat parameter
        //Patterm.CASE_INSENSITIVE, agar nilai yang akan dibandingkan tidak peduli KAPITAL
        Pattern pattern = Pattern.compile(format[tipeComboBox.getSelectedIndex()], Pattern.CASE_INSENSITIVE);

        //mencari kesamaan pattern dengan nilai paramter
        Matcher matcher = pattern.matcher(firstUniversalTextInput.getText());

        if (tipeComboBox.getSelectedIndex() == 0) { //jika nilai indeks tipeComboBox adalah 0
            try { //ekspresi try
                for (String s : format) {                           //mengulang semua pilihan pada format
                    if (matcher.find()) {                           //jika matcher menemukan kesamaan
                        return true;
                    } else {                                        //jika selain benar
                        throw new Exception();
                    }
                }
            } catch (Exception e) {                                 //menangkap Exception
                JOptionPane.showMessageDialog(this,     //menampilkan pesan dalam bentuk JOPtanePane
                        firstUniversalLabel.getText() +
                                " Hanya dapat berisi Audio, Video, Document");
            }
            return false;  //Return false, berarti nilai true tidak tercapai
        } else { //jika selain benar
            return true;  //Return false, berarti nilai true tidak tercapai
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LayerKoleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LayerKoleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LayerKoleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LayerKoleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LayerKoleksi dialog = new LayerKoleksi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JRadioButton falsebutton;
    private javax.swing.JLabel firstUniversalLabel;
    private javax.swing.JTextField firstUniversalTextInput;
    private javax.swing.JLabel idKoleksiLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel isbnLabel;
    private javax.swing.JTextField isbnTextInput;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JTextField judulTextField;
    private javax.swing.JButton kembaliButton;
    private javax.swing.JLabel namaLabel2;
    private javax.swing.JLabel penerbitLabel;
    private javax.swing.JTextField penerbitTextField;
    private javax.swing.JLabel secondUniversalLabel;
    private javax.swing.JTextField secondUniversalTextInput;
    private javax.swing.JButton simpanButton;
    private javax.swing.ButtonGroup statusPinjamButtonGroup;
    private javax.swing.JComboBox<String> tipeComboBox;
    private javax.swing.JLabel tipeLabel;
    private javax.swing.JLabel titlelabel;
    private javax.swing.JRadioButton trueButton;
    private javax.swing.JButton ulangiButton;
    // End of variables declaration//GEN-END:variables
}
