/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.PraktikumPBOL.GUIPerpustakaan;

import javax.swing.*;
import java.awt.event.ActionEvent;

/**
 *
 * @author Markus
 */
public class Perpustakaan extends javax.swing.JFrame {

    /**
     * Creates new form Perpustakaan
     */
    public Perpustakaan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        editMenu = new javax.swing.JMenu();
        peminjamMenuItem = new javax.swing.JMenuItem();
        koleksiMenuItem = new javax.swing.JMenuItem();
        transaksiMenu = new javax.swing.JMenu();
        pinjamMenuItem = new javax.swing.JMenuItem();
        kembaliMenuItem = new javax.swing.JMenuItem();
        tampilMenu = new javax.swing.JMenu();
        koleksiMenu = new javax.swing.JMenu();
        bukuMenuItem = new javax.swing.JMenuItem();
        diskMenuItem = new javax.swing.JMenuItem();
        majalahMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editMenu.setText("Edit");

        peminjamMenuItem.setText("Peminjam");
        peminjamMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peminjamMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(peminjamMenuItem);

        koleksiMenuItem.setText("Koleksi");
        koleksiMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                koleksiMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(koleksiMenuItem);

        menuBar.add(editMenu);

        transaksiMenu.setText("Transaksi");

        pinjamMenuItem.setText("Pinjam");
        transaksiMenu.add(pinjamMenuItem);

        kembaliMenuItem.setText("Kembali");
        transaksiMenu.add(kembaliMenuItem);

        menuBar.add(transaksiMenu);

        tampilMenu.setText("Tampil");

        koleksiMenu.setText("Koleksi");

        bukuMenuItem.setText("Buku");
        koleksiMenu.add(bukuMenuItem);

        diskMenuItem.setText("Disk");
        diskMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diskMenuItemActionPerformed(evt);
            }
        });
        koleksiMenu.add(diskMenuItem);

        majalahMenuItem.setText("Majalah");
        majalahMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                majalahMenuItemActionPerformed(evt);
            }
        });
        koleksiMenu.add(majalahMenuItem);

        tampilMenu.add(koleksiMenu);

        menuBar.add(tampilMenu);

        helpMenu.setText("Help");
        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void peminjamMenuItemActionPerformed(ActionEvent evt) {
        LayerPeminjam layerPeminjam = new LayerPeminjam(this, true); //instansiasi kelas LayerPeminjam
        this.setVisible(false); //Membuat GUI kelas ini tidak terlihat
        layerPeminjam.setVisible(true); //Membuat GUI Layer Peminjam terlihat

        //Jika layer Peminjam di tutup, GUI kelas ini akan terlihat kembali
        if (layerPeminjam.isActive()){
            this.setVisible(true);
        }
    }

    private void diskMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void koleksiMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        LayerKoleksi layerKoleksi = new LayerKoleksi(this, true); //Instansiasi kelas LayerKoleksi
        this.setVisible(false);//Membuat GUI kelas ini tidak terlihat
        layerKoleksi.setVisible(true); //Membuat GUI Layer Koleksi terlihat

        //Jika layer Koleksi ditutup, GUI kelas ini akan terlihat kembali
        if (layerKoleksi.isActive()){
            this.setVisible(true);
        }
    }

    private void majalahMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */    
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Perpustakaan prp = new Perpustakaan();
                prp.setResizable(false);
                prp.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bukuMenuItem;
    private javax.swing.JMenuItem diskMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem kembaliMenuItem;
    private javax.swing.JMenu koleksiMenu;
    private javax.swing.JMenuItem koleksiMenuItem;
    private javax.swing.JMenuItem majalahMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem peminjamMenuItem;
    private javax.swing.JMenuItem pinjamMenuItem;
    private javax.swing.JMenu tampilMenu;
    private javax.swing.JMenu transaksiMenu;
    // End of variables declaration//GEN-END:variables
}
